return {
    Title = "AAA Taiwu UI Dependency Consumer Prototype",
    Author = "SMD",
    Version = "0.0.1.0",
    FileId = 990058002,
    GameVersion = "1.0.58.0",
    Description = "DELETE ME: cross-MOD consumer prototype.",
    Visibility = 0,
    Dependencies = { [1] = 990058001 },
    BackendPlugins = { },
    FrontendPlugins = { [1] = "TaiwuUi.DependencyPrototype.Consumer.dll" },
    Source = 0,
    HasArchive = false,
    NeedRestartWhenSettingChanged = false,
    ChangeConfig = false,
    DefaultSettings = { },
    SettingGroups = { },
    TagList = { [1] = "Modifications" },
}

