<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <RootNamespace>TaiwuProbeFrontend</RootNamespace>
    <AssemblyName>TaiwuProbeFrontend</AssemblyName>
    <Nullable>enable</Nullable>
    <LangVersion>10</LangVersion>
    <OutputPath>..\Plugins\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <PropertyGroup>
    <GameDir>D:\SteamLibrary\steamapps\common\The Scroll Of Taiwu</GameDir>
    <ManagedDir>$(GameDir)\The Scroll of Taiwu_Data\Managed</ManagedDir>
  </PropertyGroup>

  <Import Project="..\TaiwuProbe.props" />

  <ItemGroup>
    <None Remove="*.csproj" />
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(ManagedDir)\Newtonsoft.Json.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(ManagedDir)\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="GameData.Shared">
      <HintPath>$(ManagedDir)\GameData.Shared.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="GameData.Serializer">
      <HintPath>$(ManagedDir)\GameData.Serializer.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="GameData.Utilities">
      <HintPath>$(ManagedDir)\GameData.Utilities.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TaiwuModdingLib">
      <HintPath>$(ManagedDir)\TaiwuModdingLib.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(ManagedDir)\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(ManagedDir)\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(ManagedDir)\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>$(ManagedDir)\UnityEngine.ImageConversionModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.ScreenCaptureModule">
      <HintPath>$(ManagedDir)\UnityEngine.ScreenCaptureModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(ManagedDir)\UnityEngine.UI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>$(ManagedDir)\UnityEngine.UIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>$(ManagedDir)\Unity.TextMeshPro.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
